### PR TITLE
Hactoverfest-2022 linked list is palindrome

### PR DESCRIPTION
**Pull request by Shubham2816**

### CODE REVIEW

**Comment by abhaygupta08** [comment]
Make sure to follow me and star this repository to get your PR merged.

**Comment by Shubham2816** [comment]
done pls approve now

**Comment by Shubham2816** [comment]
u have merged my file but still it is showing not accepted pls update me

image

**Comment by Shubham2816** [comment]
help me out pls

**Comment by Shubham2816** [comment]
ok f9  its done thnks
\

**Comment by Tc2r1** [comment]
@Shubham2816 This one is excluded from Hacktoberfest, **[Use Mine Instead: ](https://github.com/Tc2r1/Hacktoberfest_Interview_App)**

**Pull request merged**
