### PR TITLE
Update Merge_Sort.py

### PR DESCRIPTION
**Pull request by shahiyan7**

### CODE REVIEW

**Comment by abhaygupta08** [comment]
Please follow me and star this repository to get your PR merged.

**Comment by shahiyan7** [comment]
bro please merge my pr

**Comment by shahiyan7** [comment]
bro I have done your demands

**Comment by Tc2r1** [comment]
@shahiyan7 This one is excluded from Hacktoberfest, **[Use Mine Instead: ](https://github.com/Tc2r1/Hacktoberfest_Interview_App)**

**Pull request merged**
