### PR TITLE
Update Hello World.html

### PR DESCRIPTION
**Pull request by Vishalrai2002**
There is some change in width and height of the hello word.

### CODE REVIEW

**Comment by abhaygupta08** [comment]
Follow my account and star this repository to get it merged.

**Comment by Vishalrai2002** [comment]
> Follow my account and star this repository to get it merged.

Done.

**Comment by Vishalrai2002** [comment]
Done

**Comment by Vishalrai2002** [comment]
> Follow my account and star this repository to get it merged.

Merge my pull request

**Pull request merged**
