### PR TITLE
Second Pr

### PR DESCRIPTION
**Pull request by mohdadnan786**
HACTOBERFEST-ACCEPTED

### CODE REVIEW

**Comment by abhaygupta08** [comment]
Please follow me and star this repository to get your PR merged.

**Comment by mohdadnan786** [comment]
Yes i have star the repository and also follow your account

**Comment by mohdadnan786** [comment]
hey why my all PR of this repo got excluded

**Comment by Tc2r1** [comment]
@mohdadnan786 This one is excluded from Hacktoberfest, **[Use Mine Instead: ](https://github.com/Tc2r1/Hacktoberfest_Interview_App)**

**Pull request merged**
